naming       = "vpguard"
vm-dns       = "vpguard-vm"
admin-user   = "vproot"
web-user     = "vpweb"
website-dns  = "eager-germain.cloud"
database-pwd = "ict22o6V@porguard"
email        = "mingwei1744@gmail.com"
web-codes    = "D:/Dev/GithubProjects/ICT2206-VapourGuard/Terraform/html/"
